import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import { ReactQueryClientProvider } from "./components/ReactQuery/ReactQuery";

export const metadata: Metadata = {
  title: "OlY",
  description: "Generated by create next app",
};

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className="">
            <Navbar />
              {children}
            <Footer />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
